// Command completions writes the shell completion scripts into completions/.
// GoReleaser runs it before building, so the archives and Linux packages ship
// scripts generated by the same code as `himorime completion`.
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/nao1215/himorime/internal/cli"
)

func main() {
	dir := "completions"
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	files := map[string]string{
		"bash":       "himorime.bash",
		"zsh":        "himorime.zsh",
		"fish":       "himorime.fish",
		"powershell": "himorime.ps1",
	}
	for _, shell := range cli.Shells() {
		f, err := os.Create(filepath.Join(dir, files[shell]))
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if err := cli.WriteCompletion(f, shell); err != nil {
			_ = f.Close()
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if err := f.Close(); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}
