package cli

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/nao1215/himorime/internal/exitcode"
	"github.com/nao1215/himorime/internal/report"
)

func TestCommentPostsRegressionReportAndExitsZero(t *testing.T) {
	dir := t.TempDir()
	reportPath := filepath.Join(dir, "report.json")
	f, err := os.Create(reportPath)
	if err != nil {
		t.Fatal(err)
	}
	rep := validCommentReport()
	rep.Summary.Regression = 1
	rep.Summary.ExitCode = exitcode.Failed
	if err := report.WriteJSON(f, rep); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
	eventPath := filepath.Join(dir, "event.json")
	write(t, eventPath, workflowRunEventJSON)
	var posted string
	client := &http.Client{Transport: cliRoundTripFunc(func(req *http.Request) (*http.Response, error) {
		switch req.Method {
		case http.MethodGet:
			return cliResponse(http.StatusOK, "[]"), nil
		case http.MethodPost:
			body, _ := io.ReadAll(req.Body)
			posted = string(body)
			return cliResponse(http.StatusCreated, ""), nil
		default:
			t.Fatalf("unexpected method %s", req.Method)
			return nil, errors.New("unexpected HTTP method")
		}
	})}
	e := env{
		"GITHUB_ACTIONS": "true", "GITHUB_EVENT_NAME": "workflow_run", "GITHUB_EVENT_PATH": eventPath,
		"GITHUB_REPOSITORY": "octo/bench", "GITHUB_API_URL": "https://api.github.example", "GITHUB_TOKEN": "token",
	}
	r := runWith(t, dir, e, func(a *App) { a.HTTPClient = client }, "comment", reportPath)
	if r.code != exitcode.OK || !strings.Contains(r.stdout, "pull request #7") || !strings.Contains(posted, "Performance regression") {
		t.Fatalf("result = %+v, posted = %s", r, posted)
	}
	var payload struct {
		Body string `json:"body"`
	}
	if err := json.Unmarshal([]byte(posted), &payload); err != nil {
		t.Fatal(err)
	}
	if !strings.HasSuffix(strings.TrimSpace(payload.Body), "<sub>Generated by [himorime](https://github.com/nao1215/himorime)</sub>") {
		t.Fatalf("default POST body has no attribution footer:\n%s", payload.Body)
	}
}

func TestCommentHideFooterControlsPostedBody(t *testing.T) {
	dir := t.TempDir()
	reportPath := filepath.Join(dir, "report.json")
	f, err := os.Create(reportPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := report.WriteJSON(f, validCommentReport()); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
	eventPath := filepath.Join(dir, "event.json")
	write(t, eventPath, workflowRunEventJSON)
	var posted string
	client := &http.Client{Transport: cliRoundTripFunc(func(req *http.Request) (*http.Response, error) {
		if req.Method == http.MethodGet {
			return cliResponse(http.StatusOK, "[]"), nil
		}
		if req.Method != http.MethodPost {
			t.Fatalf("unexpected method %s", req.Method)
		}
		body, _ := io.ReadAll(req.Body)
		posted = string(body)
		return cliResponse(http.StatusCreated, ""), nil
	})}
	e := env{
		"GITHUB_ACTIONS": "true", "GITHUB_EVENT_NAME": "workflow_run", "GITHUB_EVENT_PATH": eventPath,
		"GITHUB_REPOSITORY": "octo/bench", "GITHUB_API_URL": "https://api.github.example", "GITHUB_TOKEN": "token",
	}
	r := runWith(t, dir, e, func(a *App) { a.HTTPClient = client }, "comment", "--hide-footer", reportPath)
	if r.code != exitcode.OK {
		t.Fatalf("result = %+v", r)
	}
	var payload struct {
		Body string `json:"body"`
	}
	if err := json.Unmarshal([]byte(posted), &payload); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(payload.Body, "Generated by") || strings.Contains(payload.Body, "github.com/nao1215/himorime") {
		t.Fatalf("hidden attribution remains in POST body:\n%s", payload.Body)
	}
	for _, want := range []string{"<!-- himorime:benchmark-report:v1", "Source: benchmark, run 12"} {
		if !strings.Contains(payload.Body, want) {
			t.Errorf("POST body does not contain %q:\n%s", want, payload.Body)
		}
	}
}

func TestCommentRejectsInvalidReportAndContext(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "bad.json")
	write(t, p, `{"schema_version":"99"}`)
	eventPath := filepath.Join(dir, "event.json")
	write(t, eventPath, workflowRunEventJSON)
	e := env{
		"GITHUB_ACTIONS": "true", "GITHUB_EVENT_NAME": "workflow_run", "GITHUB_EVENT_PATH": eventPath,
		"GITHUB_REPOSITORY": "octo/bench", "GITHUB_API_URL": "https://api.github.example", "GITHUB_TOKEN": "token",
	}
	if r := run(t, dir, e, "comment", p); r.code != exitcode.Config || !strings.Contains(r.stderr, "schema_version") {
		t.Fatalf("invalid report: %+v", r)
	}
	e["GITHUB_EVENT_NAME"] = "pull_request"
	if r := run(t, dir, e, "comment", p); r.code != exitcode.Usage || !strings.Contains(r.stderr, "workflow_run") {
		t.Fatalf("invalid context: %+v", r)
	}
	if r := run(t, dir, nil, "comment"); r.code != exitcode.Usage {
		t.Fatalf("missing report: %+v", r)
	}
}

func TestCommentHelpIncludesFooterControl(t *testing.T) {
	r := run(t, t.TempDir(), nil, "comment", "--help")
	if r.code != exitcode.OK || !strings.Contains(r.stdout, "--hide-footer") {
		t.Fatalf("comment --help: %+v", r)
	}
}

func validCommentReport() *report.Report {
	now := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	return &report.Report{
		SchemaVersion: report.SchemaVersion, Mode: report.ModeCompare, HimorimeVersion: "test",
		StartedAt: now, FinishedAt: now,
		Environment: report.Environment{OS: "linux", Arch: "amd64", LogicalCPUs: 1, GoVersion: "go1.test", CI: "github-actions", Tools: []report.Tool{}},
		Suites:      []report.Suite{},
	}
}

const workflowRunEventJSON = `{
  "action":"completed",
  "repository":{"full_name":"octo/bench"},
  "workflow_run":{
    "id":9001,"name":"benchmark","workflow_id":44,"run_number":12,"run_attempt":2,
    "event":"pull_request","status":"completed","conclusion":"failure","html_url":"https://github.example/octo/bench/actions/runs/9001",
    "repository":{"full_name":"octo/bench"},
    "pull_requests":[{"number":7,"base":{"repo":{"full_name":"octo/bench"}}}]
  }
}`

type cliRoundTripFunc func(*http.Request) (*http.Response, error)

func (f cliRoundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) { return f(r) }

func cliResponse(status int, body string) *http.Response {
	return &http.Response{
		StatusCode: status, Status: http.StatusText(status), Header: make(http.Header),
		Body: io.NopCloser(bytes.NewBufferString(body)),
	}
}
