package cli

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/nao1215/himorime/internal/config"
	"github.com/nao1215/himorime/internal/exitcode"
)

// Shells lists the shells `himorime completion` supports.
func Shells() []string { return []string{"bash", "zsh", "fish", "powershell"} }

func runCompletion(_ context.Context, a *App, args []string) int {
	fs, _ := newFlagSet("completion")
	operands, status, ok := parseFlags(fs, args, a.Stdout, a.Stderr)
	if !ok {
		return status
	}
	if len(operands) != 1 {
		fmt.Fprintf(a.Stderr, "himorime completion: name one shell: %s\n", strings.Join(Shells(), ", "))
		return exitcode.Usage
	}
	if err := WriteCompletion(a.Stdout, operands[0]); err != nil {
		fmt.Fprintf(a.Stderr, "himorime completion: %v\n", err)
		return exitcode.Usage
	}
	return exitcode.OK
}

type completionData struct {
	commands []string
	flags    map[string][]string
	short    map[string]string
}

func collectCompletion() completionData {
	d := completionData{flags: map[string][]string{}, short: map[string]string{}}
	for _, c := range Commands() {
		d.commands = append(d.commands, c.Name)
		d.short[c.Name] = c.Short
		fs, _ := newFlagSet(c.Name)
		for _, f := range FlagDocs(fs) {
			d.flags[c.Name] = append(d.flags[c.Name], "--"+f.Name)
		}
		d.flags[c.Name] = append(d.flags[c.Name], "--help")
		sort.Strings(d.flags[c.Name])
	}
	return d
}

func formatWords() string {
	var out []string
	for _, f := range config.Formats() {
		out = append(out, string(f))
	}
	return strings.Join(out, " ")
}

// WriteCompletion writes the completion script for shell.
func WriteCompletion(w io.Writer, shell string) error {
	d := collectCompletion()
	var sb strings.Builder
	switch shell {
	case "bash":
		bashCompletion(&sb, d)
	case "zsh":
		zshCompletion(&sb, d)
	case "fish":
		fishCompletion(&sb, d)
	case "powershell":
		powershellCompletion(&sb, d)
	default:
		return fmt.Errorf("unsupported shell %q; use one of %s", shell, strings.Join(Shells(), ", "))
	}
	_, err := io.WriteString(w, sb.String())
	return err
}

func bashCompletion(sb *strings.Builder, d completionData) {
	sb.WriteString("# bash completion for himorime; generated by `himorime completion bash`\n")
	sb.WriteString("_himorime() {\n")
	sb.WriteString("  local cur prev cmd\n")
	sb.WriteString("  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	sb.WriteString("  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	sb.WriteString("  if [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	fmt.Fprintf(sb, "    COMPREPLY=($(compgen -W %q -- \"$cur\"))\n", strings.Join(d.commands, " "))
	sb.WriteString("    return\n  fi\n")
	sb.WriteString("  cmd=\"${COMP_WORDS[1]}\"\n")
	sb.WriteString("  case \"$prev\" in\n")
	fmt.Fprintf(sb, "    --format) COMPREPLY=($(compgen -W %q -- \"$cur\")); return ;;\n", formatWords()+" text")
	sb.WriteString("    --output|--summary) COMPREPLY=($(compgen -f -- \"$cur\")); return ;;\n")
	sb.WriteString("  esac\n")
	sb.WriteString("  case \"$cmd\" in\n")
	for _, c := range d.commands {
		words := strings.Join(d.flags[c], " ")
		if c == "completion" {
			words += " " + strings.Join(Shells(), " ")
		}
		if c == "help" {
			words += " " + strings.Join(d.commands, " ")
		}
		fmt.Fprintf(sb, "    %s) COMPREPLY=($(compgen -W %q -- \"$cur\")) ;;\n", c, words)
	}
	sb.WriteString("  esac\n")
	sb.WriteString("  if [ \"${#COMPREPLY[@]}\" -eq 0 ]; then COMPREPLY=($(compgen -f -- \"$cur\")); fi\n")
	sb.WriteString("}\ncomplete -o default -F _himorime himorime\n")
}

func zshCompletion(sb *strings.Builder, d completionData) {
	sb.WriteString("#compdef himorime\n# zsh completion for himorime; generated by `himorime completion zsh`\n")
	sb.WriteString("_himorime() {\n  local -a commands\n  commands=(\n")
	for _, c := range d.commands {
		fmt.Fprintf(sb, "    '%s:%s'\n", c, strings.ReplaceAll(d.short[c], "'", ""))
	}
	sb.WriteString("  )\n  if (( CURRENT == 2 )); then\n    _describe 'command' commands\n    return\n  fi\n")
	sb.WriteString("  case \"${words[2]}\" in\n")
	for _, c := range d.commands {
		extra := ""
		if c == "completion" {
			extra = " " + strings.Join(Shells(), " ")
		}
		fmt.Fprintf(sb, "    %s) compadd -- %s%s; _files ;;\n", c, strings.Join(d.flags[c], " "), extra)
	}
	sb.WriteString("  esac\n}\ncompdef _himorime himorime\n")
}

func fishCompletion(sb *strings.Builder, d completionData) {
	sb.WriteString("# fish completion for himorime; generated by `himorime completion fish`\n")
	fmt.Fprintf(sb, "complete -c himorime -f -n '__fish_use_subcommand' -a '%s'\n", strings.Join(d.commands, " "))
	for _, c := range d.commands {
		fmt.Fprintf(sb, "complete -c himorime -n '__fish_seen_subcommand_from %s' -d '%s'\n", c, strings.ReplaceAll(d.short[c], "'", ""))
		for _, f := range d.flags[c] {
			fmt.Fprintf(sb, "complete -c himorime -n '__fish_seen_subcommand_from %s' -l %s\n", c, strings.TrimPrefix(f, "--"))
		}
	}
	fmt.Fprintf(sb, "complete -c himorime -f -n '__fish_seen_subcommand_from completion' -a '%s'\n", strings.Join(Shells(), " "))
	fmt.Fprintf(sb, "complete -c himorime -f -n '__fish_seen_subcommand_from run compare ci' -l format -a '%s'\n", formatWords())
}

func powershellCompletion(sb *strings.Builder, d completionData) {
	sb.WriteString("# PowerShell completion for himorime; generated by `himorime completion powershell`\n")
	sb.WriteString("Register-ArgumentCompleter -Native -CommandName himorime -ScriptBlock {\n")
	sb.WriteString("  param($wordToComplete, $commandAst, $cursorPosition)\n")
	sb.WriteString("  $elements = $commandAst.CommandElements | ForEach-Object { $_.ToString() }\n")
	sb.WriteString("  $flags = @{\n")
	for _, c := range d.commands {
		quoted := make([]string, 0, len(d.flags[c]))
		for _, f := range d.flags[c] {
			quoted = append(quoted, "'"+f+"'")
		}
		if c == "completion" {
			for _, s := range Shells() {
				quoted = append(quoted, "'"+s+"'")
			}
		}
		fmt.Fprintf(sb, "    '%s' = @(%s)\n", c, strings.Join(quoted, ", "))
	}
	sb.WriteString("  }\n")
	sb.WriteString("  if ($elements.Count -le 1 -or ($elements.Count -eq 2 -and $wordToComplete -ne '')) {\n")
	quoted := make([]string, 0, len(d.commands))
	for _, c := range d.commands {
		quoted = append(quoted, "'"+c+"'")
	}
	fmt.Fprintf(sb, "    $candidates = @(%s)\n", strings.Join(quoted, ", "))
	sb.WriteString("  } else {\n    $candidates = $flags[$elements[1]]\n  }\n")
	sb.WriteString("  $candidates | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n")
	sb.WriteString("    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n  }\n}\n")
}
