package prcomment

import (
	"fmt"
	"sort"
	"strings"

	"github.com/nao1215/himorime/internal/metric"
	"github.com/nao1215/himorime/internal/report"
)

type problem struct {
	kind                                             int
	benchmark, metric, reason, values, change, limit string
	gated                                            bool
}

const (
	problemError = iota
	problemRegression
	problemBudget
	problemInconclusive
	problemSkipped
	maxNotificationProblems = 10
)

// renderComment reports problems only. Full measurements belong in Actions.
func renderComment(r *report.Report, run WorkflowRun, hideFooter bool) (string, error) {
	problems := reportProblems(r)
	sort.SliceStable(problems, func(i, j int) bool { return problems[i].kind < problems[j].kind })
	var out strings.Builder
	fmt.Fprintf(&out, "<!-- himorime:benchmark-report:v2 run_id=%d workflow_id=%d run_number=%d run_attempt=%d -->\n", run.RunID, run.WorkflowID, run.RunNumber, run.RunAttempt)
	fmt.Fprintf(&out, "## himorime: %s\n\n", notificationTitle(r, problems))
	if r.Summary.FailOnInconclusive && r.Summary.Inconclusive > 0 {
		out.WriteString("Inconclusive comparisons fail this check because fail-on-inconclusive is enabled.\n\n")
	}
	shown := problems[:min(len(problems), maxNotificationProblems)]
	for kind := problemError; kind <= problemSkipped; kind++ {
		var rows []problem
		for _, p := range shown {
			if p.kind == kind {
				rows = append(rows, p)
			}
		}
		if len(rows) == 0 {
			continue
		}
		if len(rows) != len(shown) {
			fmt.Fprintf(&out, "### %s\n\n", []string{"Errors", "Regressions", "Budget violations", "Inconclusive measurements", "Skipped checks"}[kind])
		}
		writeProblems(&out, kind, rows)
	}
	if len(shown) < len(problems) {
		fmt.Fprintf(&out, "Showing %d of %d problems; remaining items are in the full report.\n\n", len(shown), len(problems))
	}
	fmt.Fprintf(&out, "[View full benchmark report and logs](<%s>)\n", run.RunURL)
	if !hideFooter {
		out.WriteString("\n<sub>Generated by [himorime](https://github.com/nao1215/himorime)</sub>\n")
	}
	body := strings.ReplaceAll(out.String(), "@", "&#64;")
	if len(body) > maxCommentBytes {
		return "", fmt.Errorf("rendered pull request comment exceeds %d bytes", maxCommentBytes)
	}
	return body, nil
}

func notificationTitle(r *report.Report, problems []problem) string {
	counts := [5]int{}
	notGated := 0
	for _, p := range problems {
		if p.kind == problemRegression && !p.gated {
			notGated++
			continue
		}
		counts[p.kind]++
	}
	switch {
	case counts[problemError] > 0:
		return "❌ " + counted(counts[problemError], "execution or measurement error")
	case counts[problemRegression] > 0 && counts[problemBudget] > 0:
		return "❌ " + counted(counts[problemRegression], "regression") + ", " + counted(counts[problemBudget], "budget violation")
	case counts[problemRegression] > 0:
		return "❌ " + counted(counts[problemRegression], "regression") + " detected"
	case counts[problemBudget] > 0:
		return "❌ " + counted(counts[problemBudget], "budget violation")
	case r.Summary.ExitCode != 0:
		return "❌ Performance checks failed"
	case counts[problemInconclusive] > 0:
		return "⚠️ " + counted(counts[problemInconclusive], "inconclusive metric comparison")
	case notGated > 0:
		return "⚠️ " + counted(notGated, "non-gating regression")
	case counts[problemSkipped] > 0:
		return "⚠️ " + counted(counts[problemSkipped], "skipped check")
	case len(r.Suites) == 0:
		return "⚠️ No measurements"
	case r.Mode == report.ModeRun:
		return "✅ Measurements completed"
	default:
		return "✅ No regressions"
	}
}

func counted(n int, noun string) string {
	if n != 1 {
		noun += "s"
	}
	return fmt.Sprintf("%d %s", n, noun)
}

func reportProblems(r *report.Report) []problem {
	var out []problem
	for _, s := range r.Suites {
		if s.Error != nil {
			out = append(out, errorProblem(s.Name, "Suite", s.Error))
		}
		for _, b := range s.Benchmarks {
			label := b.Name
			if len(r.Suites) > 1 {
				label = s.Name + " / " + label
			}
			if b.Error != nil {
				out = append(out, errorProblem(label, "Benchmark", b.Error))
			}
			for _, c := range b.Commands {
				out = append(out, commandProblems(label+" / "+c.Name, c)...)
			}
		}
	}
	return out
}

func errorProblem(label, side string, e *report.Error) problem {
	name := "Execution"
	if e.Metric != "" {
		name = metricTitle(e.Metric)
	}
	return problem{kind: problemError, benchmark: safeCell(label), metric: name + " (" + side + ")", reason: errorText(e), gated: true}
}

func commandProblems(label string, c report.Command) []problem {
	var out []problem
	for _, side := range []struct {
		name string
		m    *report.Measurement
	}{{"base", c.Base}, {"head", c.Head}} {
		if side.m != nil && side.m.Error != nil {
			out = append(out, errorProblem(label, side.name, side.m.Error))
		}
	}
	for _, name := range problemMetrics(c) {
		mc := c.Comparisons[name]
		unavailable := false
		for _, side := range []struct {
			name string
			m    *report.Measurement
		}{{"base", c.Base}, {"head", c.Head}} {
			ms := measurementMetric(side.m, name)
			if side.m != nil && side.m.Error != nil {
				unavailable = true
				continue
			}
			if ms == nil {
				continue
			}
			kind := problemSkipped
			switch ms.Status {
			case report.StatusFailed:
				kind = problemError
			case report.StatusUnsupported:
			default:
				continue
			}
			unavailable = true
			out = append(out, problem{kind: kind, benchmark: safeCell(label), metric: metricTitle(name) + " (" + side.name + ")", reason: boundedText(ms.Status+": "+ms.Reason, 240), gated: true})
		}
		if mc != nil && !unavailable {
			if p, ok := comparisonProblem(label, name, c, mc); ok {
				out = append(out, p)
			}
		}
	}
	for _, bc := range c.Budgets {
		if bc.Status == report.BudgetPass {
			continue
		}
		out = append(out, budgetProblem(label, c, bc))
	}
	if len(out) == 0 {
		kind := problemError
		switch c.Result {
		case report.ResultError, report.ResultMetricError:
		case report.ResultRegression:
			kind = problemRegression
		case report.ResultOverBudget:
			kind = problemBudget
		case report.ResultInconclusive:
			kind = problemInconclusive
		case report.ResultPass, report.ResultImproved:
			return out
		default:
			return out
		}
		out = append(out, problem{kind: kind, benchmark: safeCell(label), metric: "—", reason: safeCell(string(c.Result)), gated: true, values: "—", change: "—", limit: "—"})
	}
	return out
}

func budgetProblem(label string, c report.Command, bc report.BudgetCheck) problem {
	kind := problemBudget
	switch bc.Status {
	case report.BudgetNoData:
		kind = problemError
	case report.BudgetSkipped:
		kind = problemSkipped
	}
	return problem{kind: kind, benchmark: safeCell(label), metric: metricTitle(bc.Metric) + " " + safeCell(bc.Aggregation), values: formatMeasured(c.Head, bc.Metric, bc.Unit, bc.Actual), limit: safeCell(bc.Operator) + " " + formatValue(bc.Unit, &bc.Limit), reason: boundedText("Budget "+bc.Status+": "+bc.Reason, 240), gated: true}
}

func comparisonProblem(label, name string, c report.Command, mc *report.MetricComparison) (problem, bool) {
	if mc.DerivedFrom != "" {
		return problem{}, false
	}
	kind := problemInconclusive
	switch mc.Verdict {
	case string(report.ResultRegression):
		kind = problemRegression
	case string(report.ResultInconclusive):
	case report.VerdictSkipped:
		kind = problemSkipped
	default:
		return problem{}, false
	}
	title := metricTitle(name)
	if !mc.Gate {
		title += " (not gated)"
	}
	reason := mc.Reason
	if reason == report.ReasonAtFloor {
		reason = "At or below the measurement floor"
	}
	return problem{kind: kind, benchmark: safeCell(label), metric: title, reason: boundedText(reason, 240), gated: mc.Gate,
		values: formatMeasured(c.Base, name, mc.Unit, mc.Base) + " → " + formatMeasured(c.Head, name, mc.Unit, mc.Head),
		change: report.FormatChange(mc.ChangePercent), limit: report.FormatMetricTolerance(mc)}, true
}

func problemMetrics(c report.Command) []string {
	names := map[string]bool{}
	for name := range c.Comparisons {
		names[name] = true
	}
	for _, m := range []*report.Measurement{c.Base, c.Head} {
		if m != nil {
			for name := range m.Metrics {
				names[name] = true
			}
		}
	}
	var out []string
	for _, d := range metric.Defs() {
		if names[string(d.Name)] {
			out = append(out, string(d.Name))
			delete(names, string(d.Name))
		}
	}
	var extra []string
	for name := range names {
		extra = append(extra, name)
	}
	sort.Strings(extra)
	return append(out, extra...)
}

func writeProblems(out *strings.Builder, kind int, rows []problem) {
	switch kind {
	case problemRegression:
		out.WriteString("| Benchmark | Metric | Base → Head | Change | Limit |\n|---|---|---:|---:|---:|\n")
	case problemBudget:
		out.WriteString("| Benchmark | Metric | Measured | Limit |\n|---|---|---:|---:|\n")
	default:
		out.WriteString("| Benchmark | Metric | Reason |\n|---|---|---|\n")
	}
	for _, p := range rows {
		cells := []string{p.benchmark, p.metric, p.reason}
		if kind == problemRegression {
			cells = []string{p.benchmark, p.metric, p.values, p.change, p.limit}
		}
		if kind == problemBudget {
			cells = []string{p.benchmark, p.metric, p.values, p.limit}
		}
		fmt.Fprintf(out, "| %s |\n", strings.Join(cells, " | "))
	}
	out.WriteString("\n")
}

func metricTitle(name string) string {
	switch name {
	case "latency":
		return "Latency"
	case "cpu_total":
		return "CPU time"
	case "cpu_user":
		return "CPU user time"
	case "cpu_system":
		return "CPU system time"
	case "cpu_utilization":
		return "CPU utilization"
	case "peak_rss":
		return "Peak RSS"
	case "throughput":
		return "Throughput"
	default:
		return safeCell(name)
	}
}

func measurementMetric(m *report.Measurement, name string) *report.MetricSummary {
	if m == nil {
		return nil
	}
	return m.Metrics[name]
}

func formatMeasured(m *report.Measurement, name, unit string, value *float64) string {
	ms := measurementMetric(m, name)
	if ms != nil && ms.Status != report.StatusMeasured {
		return safeCell(ms.Status)
	}
	if ms != nil && value != nil && ms.Floor > 0 && *value <= float64(ms.Floor) {
		floor := float64(ms.Floor)
		return "≤ " + formatValue(unit, &floor)
	}
	return formatValue(unit, value)
}

func formatValue(unit string, v *float64) string {
	if v == nil {
		return "—"
	}
	switch unit {
	case "ns":
		return metric.Format(metric.KindDuration, *v, "")
	case "bytes":
		return metric.Format(metric.KindBytes, *v, "")
	case "percent":
		return metric.Format(metric.KindPercent, *v, "")
	default:
		if strings.HasSuffix(unit, "/s") {
			return safeCell(metric.Format(metric.KindRate, *v, strings.TrimSuffix(unit, "/s")))
		}
		return fmt.Sprintf("%g %s", *v, safeCell(unit))
	}
}

func errorText(e *report.Error) string {
	text := e.Kind + ": " + e.Message
	if e.ExitCode != nil {
		text += fmt.Sprintf(" (exit %d)", *e.ExitCode)
	}
	return boundedText(text, 240)
}

func safeCell(s string) string { return boundedText(s, 120) }

func boundedText(s string, limit int) string {
	r := []rune(strings.Join(strings.Fields(s), " "))
	if len(r) > limit {
		s = string(r[:limit]) + "… [truncated; see full report]"
	} else {
		s = string(r)
	}
	if s == "" {
		return "—"
	}
	return report.EscapeMarkdown(s)
}
