package prcomment

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/nao1215/himorime/internal/exitcode"
	"github.com/nao1215/himorime/internal/report"
)

func TestMainPostsValidReportAndKeepsRegressionExitIndependent(t *testing.T) {
	dir := t.TempDir()
	reportPath := filepath.Join(dir, "report.json")
	f, err := os.Create(reportPath)
	if err != nil {
		t.Fatal(err)
	}
	rep := validReport()
	rep.Summary = report.Summary{Regression: 1, ExitCode: exitcode.Failed}
	if err := report.WriteJSON(f, rep); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
	var posted string
	client := &http.Client{Transport: roundTripFunc(func(req *http.Request) (*http.Response, error) {
		if req.Method == http.MethodGet {
			return response(http.StatusOK, "[]"), nil
		}
		data, _ := io.ReadAll(req.Body)
		posted = string(data)
		return response(http.StatusCreated, `{"id":99}`), nil
	})}
	var stdout, stderr bytes.Buffer
	code := Main(context.Background(), []string{reportPath}, &stdout, &stderr, Dependencies{
		LookupEnv: lookup(map[string]string{
			"GITHUB_ACTIONS": "true", "GITHUB_EVENT_NAME": "workflow_run", "GITHUB_EVENT_PATH": "/event.json",
			"GITHUB_REPOSITORY": "octo/bench", "GITHUB_API_URL": "https://api.example", "GITHUB_TOKEN": "token",
		}),
		ReadFile: files(workflowPayload), HTTP: client,
	})
	if code != exitcode.OK || stderr.Len() != 0 || !strings.Contains(stdout.String(), "pull request #7") {
		t.Fatalf("code = %d, stdout = %q, stderr = %q", code, stdout.String(), stderr.String())
	}
	var payload struct {
		Body string `json:"body"`
	}
	if err := json.Unmarshal([]byte(posted), &payload); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"Performance checks failed", "benchmark-report:v2 run_id=9001", "Generated by [himorime](https://github.com/nao1215/himorime)"} {
		if !strings.Contains(payload.Body, want) {
			t.Errorf("posted body lacks %q:\n%s", want, payload.Body)
		}
	}
}

func TestMainHelpAndExitSemantics(t *testing.T) {
	tests := []struct {
		name string
		args []string
		deps Dependencies
		want int
		text string
	}{
		{name: "help", args: []string{"--help"}, want: exitcode.OK, text: "--hide-footer"},
		{name: "missing report", want: exitcode.Usage, text: "exactly one"},
		{name: "untrusted context", args: []string{"missing.json"}, deps: Dependencies{LookupEnv: lookup(map[string]string{})}, want: exitcode.Usage, text: "workflow_run"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var stdout, stderr bytes.Buffer
			code := Main(context.Background(), tt.args, &stdout, &stderr, tt.deps)
			if code != tt.want || !strings.Contains(stdout.String()+stderr.String(), tt.text) {
				t.Fatalf("code = %d, stdout = %q, stderr = %q", code, stdout.String(), stderr.String())
			}
			if code == exitcode.Usage && !strings.HasPrefix(stderr.String(), "HMR3001: ") {
				t.Fatalf("missing diagnostic code: %s", stderr.String())
			}
		})
	}
}

func TestMainLogsBeforePublicationAndLinksToReportingRun(t *testing.T) {
	for _, scenario := range []string{"summary", "missing summary", "unwritable summary", "publication fails"} {
		t.Run(scenario, func(t *testing.T) {
			dir := t.TempDir()
			path := filepath.Join(dir, "report.json")
			f, err := os.Create(path)
			if err != nil {
				t.Fatal(err)
			}
			if err := report.WriteJSON(f, validReport()); err != nil {
				t.Fatal(err)
			}
			if err := f.Close(); err != nil {
				t.Fatal(err)
			}
			values := map[string]string{"GITHUB_ACTIONS": "true", "GITHUB_EVENT_NAME": "workflow_run", "GITHUB_EVENT_PATH": "/event.json", "GITHUB_REPOSITORY": "octo/bench", "GITHUB_API_URL": "https://api.example", "GITHUB_TOKEN": "secret", "GITHUB_SERVER_URL": "https://github.com", "GITHUB_RUN_ID": "12345"}
			if scenario == "summary" {
				values["GITHUB_STEP_SUMMARY"] = filepath.Join(dir, "summary.md")
			}
			if scenario == "unwritable summary" {
				values["GITHUB_STEP_SUMMARY"] = dir
			}
			var stdout, stderr bytes.Buffer
			var posted string
			client := &http.Client{Transport: roundTripFunc(func(req *http.Request) (*http.Response, error) {
				if !strings.Contains(stdout.String(), "| himorime | test |") {
					t.Error("full report missing before publication")
				}
				if req.Method == http.MethodGet {
					return response(http.StatusOK, "[]"), nil
				}
				data, _ := io.ReadAll(req.Body)
				var payload struct {
					Body string `json:"body"`
				}
				if err := json.Unmarshal(data, &payload); err != nil {
					t.Fatal(err)
				}
				posted = payload.Body
				if scenario == "publication fails" {
					return response(http.StatusForbidden, "denied"), nil
				}
				return response(http.StatusCreated, `{"id":99}`), nil
			})}
			code := Main(context.Background(), []string{path}, &stdout, &stderr, Dependencies{LookupEnv: lookup(values), ReadFile: files(workflowPayload), HTTP: client})
			want := exitcode.OK
			if scenario == "publication fails" {
				want = exitcode.Execution
			}
			if code != want {
				t.Fatalf("code=%d stderr=%s", code, stderr.String())
			}
			if !strings.Contains(posted, "actions/runs/12345") || !strings.Contains(posted, "run_id=9001") {
				t.Fatalf("identity or report link lost: %s", posted)
			}
			if !strings.Contains(stdout.String(), "https://github.example/octo/bench/actions/runs/9001") {
				t.Fatal("source run lost")
			}
			if scenario == "summary" {
				data, err := os.ReadFile(values["GITHUB_STEP_SUMMARY"])
				if err != nil || !strings.Contains(string(data), "| himorime | test |") {
					t.Fatalf("summary=%s, err=%v", data, err)
				}
			}
		})
	}
}

func validReport() *report.Report {
	now := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	return &report.Report{
		SchemaVersion: report.SchemaVersion, Mode: report.ModeCompare, HimorimeVersion: "test", StartedAt: now, FinishedAt: now,
		Environment: report.Environment{OS: "linux", Arch: "amd64", LogicalCPUs: 1, GoVersion: "go1.test", CI: "github-actions", Tools: []report.Tool{}},
		Suites:      []report.Suite{},
	}
}

func lookup(values map[string]string) func(string) (string, bool) {
	return func(key string) (string, bool) {
		value, ok := values[key]
		return value, ok
	}
}
