package ghactions

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"testing"

	"github.com/nao1215/himorime/internal/report"
)

const workflowPayload = `{
  "action":"completed",
  "repository":{"full_name":"octo/bench"},
  "workflow_run":{
    "id":9001,"name":"benchmark","workflow_id":44,"run_number":12,"run_attempt":2,
    "event":"pull_request","status":"completed","conclusion":"failure","html_url":"https://github.example/octo/bench/actions/runs/9001",
    "repository":{"full_name":"octo/bench"},
    "pull_requests":[{"number":7,"base":{"repo":{"full_name":"octo/bench"}}}]
  }
}`

func workflowEnv() Env {
	return env(map[string]string{
		"GITHUB_ACTIONS": "true", "GITHUB_EVENT_NAME": "workflow_run", "GITHUB_EVENT_PATH": "/event.json",
		"GITHUB_REPOSITORY": "octo/bench", "GITHUB_API_URL": "https://api.github.example", "GITHUB_TOKEN": "secret",
	})
}

func TestResolveWorkflowRun(t *testing.T) {
	t.Parallel()
	run, err := workflowEnv().ResolveWorkflowRun(files(workflowPayload))
	if err != nil || run.Repository != "octo/bench" || run.PullRequest != 7 || run.WorkflowID != 44 || run.RunNumber != 12 || run.RunAttempt != 2 {
		t.Fatalf("run = %+v, err = %v", run, err)
	}
	tests := []struct{ name, payload, event, repo, want string }{
		{"wrong event", workflowPayload, "pull_request", "octo/bench", "only available"},
		{"foreign repository", strings.Replace(workflowPayload, `"full_name":"octo/bench"`, `"full_name":"evil/repo"`, 1), "workflow_run", "octo/bench", "does not match"},
		{"not a pull request workflow", strings.Replace(workflowPayload, `"event":"pull_request"`, `"event":"push"`, 1), "workflow_run", "octo/bench", "want pull_request"},
		{"no associated pull request", strings.Replace(workflowPayload, `"pull_requests":[{"number":7,"base":{"repo":{"full_name":"octo/bench"}}}]`, `"pull_requests":[]`, 1), "workflow_run", "octo/bench", "exactly one"},
		{"foreign pull request", strings.Replace(workflowPayload, `"full_name":"octo/bench"}}}]`, `"full_name":"evil/repo"}}}]`, 1), "workflow_run", "octo/bench", "does not belong"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			e := env(map[string]string{"GITHUB_ACTIONS": "true", "GITHUB_EVENT_NAME": tt.event, "GITHUB_EVENT_PATH": "/e", "GITHUB_REPOSITORY": tt.repo})
			_, err := e.ResolveWorkflowRun(files(tt.payload))
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("err = %v, want %q", err, tt.want)
			}
		})
	}
}

func TestRenderCommentEscapesHostileNamesAndIsBounded(t *testing.T) {
	t.Parallel()
	rep := &report.Report{Mode: report.ModeCompare, Summary: report.Summary{Regression: 1, ExitCode: 1}}
	rep.Suites = []report.Suite{{Name: "@org/team suite|<script>alert(1)</script>", Result: report.ResultRegression, Benchmarks: []report.Benchmark{{Name: "line\nbreak", Result: report.ResultRegression, Commands: []report.Command{{Name: "[bad](javascript:x)", Result: report.ResultRegression}}}}}}
	run := WorkflowRun{WorkflowID: 44, WorkflowName: "@org/team bench [x]", RunNumber: 12, RunAttempt: 2, RunURL: "https://github.example/run/1", Conclusion: "failure"}
	body, err := RenderComment(rep, run, CommentRenderOptions{})
	if err != nil {
		t.Fatal(err)
	}
	for _, bad := range []string{"<script>", "\nline\nbreak", "[bad](javascript:x)", "@org/team"} {
		if strings.Contains(body, bad) {
			t.Errorf("body contains unsafe %q:\n%s", bad, body)
		}
	}
	for _, want := range []string{"<!-- himorime:benchmark-report:v1 workflow_id=44 run_number=12 run_attempt=2 -->", "Performance regression", "&#64;org/team", "<details>", "suite\\|&lt;script&gt;", "— failure", "<sub>Generated by [himorime](https://github.com/nao1215/himorime)</sub>"} {
		if !strings.Contains(body, want) {
			t.Errorf("body does not contain %q:\n%s", want, body)
		}
	}
	if len(body) > maxCommentBytes {
		t.Fatalf("body has %d bytes", len(body))
	}
	if !strings.HasSuffix(strings.TrimSpace(body), "<sub>Generated by [himorime](https://github.com/nao1215/himorime)</sub>") {
		t.Fatalf("attribution is not the final visible line:\n%s", body)
	}
}

func TestRenderCommentCanHideAttributionFooter(t *testing.T) {
	t.Parallel()
	rep := &report.Report{Mode: report.ModeRun, Summary: report.Summary{Pass: 1}}
	run := WorkflowRun{WorkflowID: 44, WorkflowName: "bench", RunNumber: 12, RunAttempt: 2, RunURL: "https://github.example/run/1", Conclusion: "success"}
	body, err := RenderComment(rep, run, CommentRenderOptions{HideFooter: true})
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(body, "Generated by") || strings.Contains(body, "github.com/nao1215/himorime") {
		t.Fatalf("hidden footer remains in comment:\n%s", body)
	}
	for _, want := range []string{"<!-- himorime:benchmark-report:v1", "Source: bench, run 12"} {
		if !strings.Contains(body, want) {
			t.Errorf("body does not contain %q:\n%s", want, body)
		}
	}
}

func TestRenderCommentIncludesAggregatedMetrics(t *testing.T) {
	t.Parallel()
	stats := &report.MetricStats{Count: 3, Min: 9_000_000, Max: 11_000_000, Mean: 10_000_000, Median: 10_000_000, Percentiles: map[string]float64{"p95": 11_000_000}}
	measurement := &report.Measurement{Count: 3, Metrics: map[string]*report.MetricSummary{
		"latency": {Name: "latency", Group: "latency", Unit: "ns", Better: "lower", Status: report.StatusMeasured, Stats: stats},
	}}
	rep := &report.Report{Mode: report.ModeRun, Summary: report.Summary{Pass: 1}}
	rep.Suites = []report.Suite{{Name: "suite", Result: report.ResultPass, Benchmarks: []report.Benchmark{{Name: "case", Result: report.ResultPass, Commands: []report.Command{{Name: "tool", Result: report.ResultPass, Head: measurement}}}}}}
	run := WorkflowRun{WorkflowID: 44, WorkflowName: "bench", RunNumber: 12, RunAttempt: 2, RunURL: "https://github.example/run/1", Conclusion: "success"}
	body, err := RenderComment(rep, run, CommentRenderOptions{})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"<summary>Benchmark details</summary>", "Median", "10.00ms"} {
		if !strings.Contains(body, want) {
			t.Errorf("body does not contain %q:\n%s", want, body)
		}
	}
}

func TestRenderCommentFallsBackToCompactTable(t *testing.T) {
	t.Parallel()
	rep := &report.Report{Mode: report.ModeRun, Summary: report.Summary{Pass: 1}}
	rep.Suites = []report.Suite{{Name: "suite", Description: strings.Repeat("x", maxCommentBytes), Result: report.ResultPass, Benchmarks: []report.Benchmark{{Name: "case", Result: report.ResultPass, Commands: []report.Command{{Name: "tool", Result: report.ResultPass}}}}}}
	run := WorkflowRun{WorkflowID: 44, WorkflowName: "bench", RunNumber: 12, RunAttempt: 2, RunURL: "https://github.example/run/1", Conclusion: "success"}
	body, err := RenderComment(rep, run, CommentRenderOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(body, "<details>") || !strings.Contains(body, "| Suite") || len(body) > maxCommentBytes {
		t.Fatalf("fallback was not compact (%d bytes):\n%s", len(body), body)
	}
}

func TestCommentClientPaginatesAndUpdatesOwnedComment(t *testing.T) {
	t.Parallel()
	const token = "top-secret-token"
	var requests []string
	httpClient := &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		requests = append(requests, r.Method+" "+r.URL.RequestURI())
		if r.Header.Get("Authorization") != "Bearer "+token {
			t.Errorf("authorization = %q", r.Header.Get("Authorization"))
		}
		switch {
		case r.Method == http.MethodGet && r.URL.Query().Get("page") == "1":
			comments := make([]issueComment, 100)
			var b strings.Builder
			if err := json.NewEncoder(&b).Encode(comments); err != nil {
				t.Fatal(err)
			}
			return response(http.StatusOK, b.String()), nil
		case r.Method == http.MethodGet && r.URL.Query().Get("page") == "2":
			return response(http.StatusOK, `[{
              "id":81,"body":"<!-- himorime:benchmark-report:v1 workflow_id=44 run_number=11 run_attempt=1 -->",
              "user":{"login":"github-actions[bot]","type":"Bot"}
            }]`), nil
		case r.Method == http.MethodPatch && strings.HasSuffix(r.URL.Path, "/issues/comments/81"):
			return response(http.StatusOK, ""), nil
		default:
			t.Errorf("unexpected request: %s %s", r.Method, r.URL.String())
			return response(http.StatusNotFound, ""), nil
		}
	})}
	run := WorkflowRun{Repository: "octo/bench", PullRequest: 7, WorkflowID: 44, RunNumber: 12, RunAttempt: 1}
	c := CommentClient{HTTP: httpClient, APIURL: "https://api.example/api/v3", Token: token, Repository: "octo/bench"}
	stale, err := c.Upsert(context.Background(), run, "body")
	if err != nil || stale {
		t.Fatalf("stale = %v, err = %v", stale, err)
	}
	if len(requests) != 3 || !strings.Contains(requests[0], "/api/v3/repos/octo/bench/issues/7/comments?") || !strings.Contains(requests[1], "page=2") || !strings.Contains(requests[2], "/api/v3/repos/octo/bench/issues/comments/81") {
		t.Fatalf("requests = %v", requests)
	}
}

func TestCommentClientRejectsStaleRunAndDoesNotLeakToken(t *testing.T) {
	t.Parallel()
	const token = "never-print-me"
	mutated := false
	httpClient := &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		if r.Method != http.MethodGet {
			mutated = true
		}
		return response(http.StatusOK, `[{"id":1,"body":"<!-- himorime:benchmark-report:v1 workflow_id=44 run_number=13 run_attempt=1 -->","user":{"login":"github-actions[bot]","type":"Bot"}}]`), nil
	})}
	run := WorkflowRun{Repository: "octo/bench", PullRequest: 7, WorkflowID: 44, RunNumber: 12, RunAttempt: 9}
	c := CommentClient{HTTP: httpClient, APIURL: "https://api.example", Token: token, Repository: "octo/bench"}
	stale, err := c.Upsert(context.Background(), run, "body")
	if err != nil || !stale || mutated {
		t.Fatalf("stale = %v, mutated = %v, err = %v", stale, mutated, err)
	}

	c.HTTP = &http.Client{Transport: roundTripFunc(func(*http.Request) (*http.Response, error) {
		return response(http.StatusForbidden, token), nil
	})}
	_, err = c.Upsert(context.Background(), run, "body")
	if err == nil || strings.Contains(err.Error(), token) {
		t.Fatalf("err = %q; token must not be exposed", err)
	}
}

func TestCommentClientDoesNotUpdateAnUnownedMarker(t *testing.T) {
	t.Parallel()
	created := false
	httpClient := &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		if r.Method == http.MethodGet {
			return response(http.StatusOK, `[{"id":1,"body":"<!-- himorime:benchmark-report:v1 workflow_id=44 run_number=99 run_attempt=1 -->","user":{"login":"attacker","type":"User"}}]`), nil
		}
		created = r.Method == http.MethodPost && strings.HasSuffix(r.URL.Path, "/issues/7/comments")
		return response(http.StatusCreated, ""), nil
	})}
	run := WorkflowRun{Repository: "octo/bench", PullRequest: 7, WorkflowID: 44, RunNumber: 12, RunAttempt: 1}
	c := CommentClient{HTTP: httpClient, APIURL: "https://api.example", Token: "token", Repository: "octo/bench"}
	if stale, err := c.Upsert(context.Background(), run, "body"); err != nil || stale || !created {
		t.Fatalf("stale = %v, created = %v, err = %v", stale, created, err)
	}
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) { return f(r) }

func response(status int, body string) *http.Response {
	return &http.Response{
		StatusCode: status,
		Status:     fmt.Sprintf("%d %s", status, http.StatusText(status)),
		Header:     make(http.Header),
		Body:       io.NopCloser(strings.NewReader(body)),
	}
}
